from setuptools import setup, find_packages

setup(
    name="deeptimer",
    version="0.1.0",
    description="A multitask deep learning model for time-to-event analysis",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Deniz Akdemir",
    author_email="deniz.akdemir.work@gmail.com",
    url="https://github.com/denizakdemir/DeepTimeR",
    packages=find_packages(),
    install_requires=[
        "tensorflow>=2.8.0",
        "numpy>=1.19.0",
        "pandas>=1.2.0",
        "scikit-learn>=0.24.0",
        "matplotlib>=3.3.0",
        "lifelines>=0.27.0",
        "shap>=0.40.0",
        "lime>=0.2.0",
    ],
    python_requires=">=3.7",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Scientific/Engineering :: Medical Science Apps.",
    ],
    keywords="survival analysis, competing risks, multi-state model, deep learning, time-to-event",
    project_urls={
        "Documentation": "https://deeptimer.readthedocs.io",
        "Source": "https://github.com/denizakdemir/DeepTimeR",
        "Issue Tracker": "https://github.com/denizakdemir/DeepTimeR/issues",
    },
) 